services:
  book-api-db:
    build: ./deploy/db
    ports:
      - "33066:3306"
  book-api-server:
    build: .
    ports:
      - "8010:8010"
    env_file:
      - ./deploy/docker/book_api_server.env
    depends_on:
      - "book-api-db"

